export default [
    {
        id: 1,
        name: "Refrigerante Coca-Cola 2L",
        price: 10.50,
        description: "Refrigerante Coca-Cola 2L",
        image: "https://pub-cfffccb2abb548a3ab74ccaf93a42397.r2.dev/1.webp",
    },
    {
        id: 2,
        name: "Arroz Branco Tio Urbano 1kg",
        price: 10.00,
        description: "O Arroz tio Urbano é reconhecido em todo o Brasil pela sua qualidade e sabor. Com mais de 60 anos de tradição, a Urbano é referência em arroz e suas marcas",
        image: "https://pub-cfffccb2abb548a3ab74ccaf93a42397.r2.dev/2.webp",
    },
    {
        id: 3,
        name: "Sabonete Dove",
        price: 2.49,
        description: "Sabonete Dove Original 90g",
        image: "https://pub-cfffccb2abb548a3ab74ccaf93a42397.r2.dev/3.webp",
    },
    {
        id: 4,
        name: "Tomate",
        price: 3.00,
        description: "Tomate Fresco (1kg)",
        image: "https://pub-cfffccb2abb548a3ab74ccaf93a42397.r2.dev/4.webp",
    },
    {
        id: 5,
        name: "Pote de Açaí Grande",
        price: 23.50,
        description: "1L",
        image: "https://pub-cfffccb2abb548a3ab74ccaf93a42397.r2.dev/5.webp",
    },
    {
        id: 6,
        name: "Leite Integral",
        price: 4.00,
        description: "O Leite Integral Piracanjuba é uma opção saborosa e nutritiva, perfeito para o dia a dia. Rico em cálcio e vitaminas, é ideal para acompanhar cafés, preparar sobremesas ou consumir puro. Embalagem prática e segura com tecnologia de longa vida. Qualidade garantida por uma das marcas mais tradicionais do Brasil.",
        image: "https://pub-cfffccb2abb548a3ab74ccaf93a42397.r2.dev/6.webp",
    },
    {
        id: 7,
        name: "Leite em pó Integral 400g Camponesa",
        price: 8.00,
        description: "Leite em Pó Camponesa Integral 400g",
        image: "https://pub-cfffccb2abb548a3ab74ccaf93a42397.r2.dev/7.webp",
    },
    {
        id: 8,
        name: "Veja Limpador Multiuso Gold Original 750Ml",
        price: 11.00,
        description: "Aplique o produto nas superfícies a serem limpas e, em seguida passe um pano ou esponja macia. Para sujeiras mais difíceis, deixar o produto agir por alguns instantes.",
        image: "https://pub-cfffccb2abb548a3ab74ccaf93a42397.r2.dev/8.webp",
    },
    {
        id: 9,
        name: "Peito de Frango Natto 1Kg",
        price: 15.00,
        description: "Peito de Frango Congelado Natto 1Kg",
        image: "https://pub-cfffccb2abb548a3ab74ccaf93a42397.r2.dev/9.webp",
    },
];
